name: LISATools Comparison Tests

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]
  schedule:
    # Run tests at 7:00 UTC everyday
    - cron: '0 7 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lisatools-comparison:
    name: LISATools Comparison Tests

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test,comparison]
    - name: Run bilby compatibility tests
      run: |
        python -m pytest -m "comparison"
